name: Deploy Helm Chart to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_SUBSCRIPTION_ID: "c9e7611c-d508-4-f-aede-0bedfabc1560"  # Replace with your Azure subscription ID
  RESOURCE_GROUP_NAME: "random-aks-resource-group"  # Replace with your resource group name
  AKS_CLUSTER_NAME: "random-aks-cluster"  # Replace with your AKS cluster name
  SOURCE_ACR: "reference.azurecr.io"  # Source Azure Container Registry
  TARGET_ACR: "instance.azurecr.io"  # Target Azure Container Registry
  CHARTS_TO_IMPORT: "chart1:1.0.0 chart2:1.2.0"  # Charts to import (space-separated list)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Azure CLI using a Service Principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5  # Specify Terraform version

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Apply Terraform to import Helm charts from source ACR to target ACR
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        env:
          ARM_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      # Step 6: Get AKS credentials
      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP_NAME }} --name ${{ env.AKS_CLUSTER_NAME }}

      # Step 7: Install Helm in the runner
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # Step 8: Add Target ACR to Helm Repo
      - name: Add ACR to Helm Repo
        run: helm repo add target-acr https://${{ env.TARGET_ACR }}

      # Step 9: Install Helm Chart from the Target ACR
      - name: Install Helm Chart
        run: |
          helm install release target-acr/<CHART_NAME> --version <CHART_VERSION> --set key1=value1,key2=value2
